#:schema https://github.com/jdx/mise/raw/main/schema/mise.json

[tools]
# Languages
node = "lts"
go = "latest"
python = "latest"

[settings]
python.uv_venv_auto = true

trusted_config_paths = ['~/projects', '~/code']
env_file = '.env'

lockfile = true
experimental = true
