#:schema https://github.com/jdx/mise/raw/main/schema/mise.json

[tools]
# Languages
node = "lts"
go = "latest"
python = "latest"

[settings]
python.uv_venv_auto = true

trusted_config_paths = ['~/projects', '~/code']
env_file = '.env'

lockfile = true
experimental = true

auto_install_disable_tools = [
  # Heavy Tools
  "go",
  "node",
  "k9s",

  # Go dev stack
  "gopls",
  "golangci-lint",
  "golangci-lint-langserver",
  "delve",
]
