#!/bin/sh

case "$1" in
        *.tgz|*.tar.gz) tar tzf "$1";;
        *.tar.bz2|*.tbz2) tar tjf "$1";;;
        *.tar) tar tf "$1";;
        *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
        *.csv) cat "$1" | sed s/,/\\n/g ;;
        *) bat_lf.sh "$1";;
esac
