-- Base
require("ian.options")
require("ian.keymaps")
require("ian.plugins")
require("ian.colorscheme")

-- LSP
require("ian.cmp")
require("ian.lsp")
require("ian.telescope")
require("ian.treesitter")
require("ian.autopairs")
require("ian.comment")
require("ian.gitsigns")
require("ian.nvim-tree")
require("ian.bufferline")
require("ian.lsp.null-ls")
require("ian.lualine")
require("ian.toggleterm")
require("ian.project")
require("ian.impatient")
require("ian.indentline")
require("ian.alpha")
require("ian.whichkey")
require("ian.autocommands")
