[tools]
# General
atuin = "latest"
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ripgrep = "latest"
television = "latest"
tmux = "latest"
"aqua:joshmedeski/sesh" = "latest"

# Shell prompts
"aqua:JanDeDobbeleer/oh-my-posh" = "latest"
# starship = "latest"

# Editors
neovim = "latest"
yazi = "latest"

# Structured parsing
fx = "latest"
jless = "latest"
jmespath = "latest"
jq = "latest"
jqp = "latest"
tree-sitter = "latest"
yq = "latest"

# Git
github-cli = "latest"
lazygit = "latest"
glab = "latest"

# API testing
hurl = "latest"
xh = "latest"

# Python
ruff = "latest"
uv = "latest"
ty = "latest"
# "npm:basedpyright" = "latest"

# Go
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"

# Lua
stylua = "latest"
lua-language-server = "latest"

# Shell
shellcheck = "latest"
shfmt = "latest"
"npm:bash-language-server" = "latest"

# Ansible
# "npm:@ansible/ansible-language-server" = "latest"

# YAML
yamllint = "latest"
"npm:yaml-language-server" = "latest"

# TOML
taplo = "latest"

# HTML/JSON/XML
oxfmt = "latest"
"npm:vscode-langservers-extracted" = "latest"

# Markdown
marksman = "latest"

# Kubernetes
k9s = "latest"
kubectx = "latest"
kubens = "latest"

# Docker
nerdctl = "latest"
hadolint = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"

# Cloud
aws-cli = "latest"
opentofu = "latest"
"aqua:opentofu/tofu-ls" = "latest"
# terraform = "latest"
# terraform-ls = "latest"
