format = '$all'
scan_timeout = 30
command_timeout = 500
add_newline = false

[cmd_duration]
disabled = true

[package]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_length = 3
style = "bold blue"

[python]
detect_extensions = []
symbol = ' '
version_format = "v${major}.${minor}"
