---
- name: "Set up development environment"
  hosts: localhost
  connection: local
  become: yes

  vars:
    default_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    home_path: "{{ lookup('ansible.builtin.env', 'HOME') }}"

  tasks:
    
  - name: "{{ item.description }}"
    ansible.builtin.dnf:
      name: "{{ item.packages }}"
      state: latest
    loop:
      - description: "Update existing system packages"
        packages: "*"
      - description: "Install initial tools"
        packages:
          - git
          - gcc
          - gcc-c++
          - unzip
          - make
          - tmux
          - zsh

  - name: "Initialize Tmux Package Manager"
    ansible.builtin.git:
      repo: https://github.com/tmux-plugins/tpm
      dest: "{{ home_path }}/.tmux/plugins/tpm"

  - name: "Copy over config files"
    ansible.builtin.copy:
      src: ../xdg_config/
      dest: "{{ home_path }}/.config/"
      owner: "{{ default_user }}"
      group: "{{ default_user }}"

    # TODO: Move rtx into role
  - name: "Download rtx"
    ansible.builtin.get_url:
      url: https://rtx.pub/rtx-latest-linux-x64
      dest: "{{ home_path }}/.local/bin/rtx"
      owner: "{{ default_user }}"
      mode: "0774"
