[tools]
# Languages
node = "lts"
go = "latest"
python = "latest"

[settings]
python.uv_venv_auto = true

trusted_config_paths = [
    '~/projects',
    '~/code',
]
env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`

experimental = true # enable experimental features
